stages:

  create_data:
    cmd: python src/data_load/create_dataframe.py --config=params.yaml --test_size=0.3
    deps:
      - src/data_load/create_dataframe.py
    outs:
      - data/raw/train_df.parquet
      - data/raw/test_df.parquet

  build_train:
    cmd: python src/feature/build_feature.py --mode=train
    deps:
      - src/feature/build_feature.py
      - data/raw/train_df.parquet
    outs:
      - data/processed/train_dataset.pkl

  build_test:
    cmd: python src/feature/build_feature.py --mode=test
    deps:
      - src/feature/build_feature.py
      - data/raw/test_df.parquet
      - data/processed/train_dataset.pkl
    outs:
      - data/processed/test_dataset.pkl

  train_model:
    cmd: python src/model/train_model.py --epoch=3
    deps:
      - src/model/train_model.py
      - src/model/model.py
      - data/processed/train_dataset.pkl
      - data/processed/test_dataset.pkl
    outs:
      - models/model.torch
